/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package concesionario.vista;
import concesionario.clases.*;
import concesionario.util.Validar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author javip
 */
public class Menu extends javax.swing.JFrame {
    Concesionario concesionario;
    /**
     * Creates new form NewJFrame
     */
    public Menu() {
        initComponents();
    }

    public Menu(Concesionario concesionario) {
        initComponents();
        this.concesionario = concesionario;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Insertar Vehiculo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Buscar Vehículo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar Vehículo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mostrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Modificar kms");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Gestión de Taller");

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   //insertar vehiculo
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame insertar = new Insertar(concesionario);
        //a seguinte linea fai que non se cerre a aplicación ó cerrar a ventá de insertar
        insertar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //centramos a ventana
        insertar.setLocationRelativeTo(null);
        //mostramos o formulario
        insertar.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    //buscar vehiculo
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String entradaUsuario = JOptionPane.showInputDialog(null,"Introduce  la Matrícula:","Buscar Vehiculo",JOptionPane.QUESTION_MESSAGE);
        if (entradaUsuario.equals("")){
           JOptionPane.showMessageDialog(null,"El campo matrícula está vacío", "Error en la entrada",JOptionPane.ERROR_MESSAGE);
        }
        else if (!Validar.validarMatricula(entradaUsuario)){
           JOptionPane.showMessageDialog(null,"El campo matrícula no es correcto", "Error en la entrada",JOptionPane.ERROR_MESSAGE);
        } else {
            
            String busqueda = concesionario.buscarVehiculo(entradaUsuario);
            if (busqueda == null){
                JOptionPane.showMessageDialog(null,"No se encuentra el Vehículo", "Error",JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null,busqueda, "Mostrando Vehículo",JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        //pulsando salir cerramos la aplicación
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    //eliminar vehiculo
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String entradaUsuario = JOptionPane.showInputDialog(null,"Introduce  la Matrícula:", "Eliminar Vehiculo", JOptionPane.QUESTION_MESSAGE);
        if (entradaUsuario.equals("")){
           JOptionPane.showMessageDialog(null,"El campo matrícula está vacío", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
        }
        else if (!Validar.validarMatricula(entradaUsuario)){
           JOptionPane.showMessageDialog(null,"El campo matrícula no es correcto", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
        } else {
            //miramos se está
           String busqueda = concesionario.buscarVehiculo(entradaUsuario);
            if (busqueda == null){
                JOptionPane.showMessageDialog(null, "No se encuentra el Vehículo", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                concesionario.eliminarVehiculo(entradaUsuario);
                JOptionPane.showMessageDialog(null, "Vehiculo Eliminado", "Eliminando Vehículo", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    

    //modificar kms
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String entradaUsuario = JOptionPane.showInputDialog(null, "Introduce  la Matrícula:", "Modificar Kilómetros", JOptionPane.QUESTION_MESSAGE);
        if (entradaUsuario.equals("")){
           JOptionPane.showMessageDialog(null,"El campo matrícula está vacío", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
        }
        else if (!Validar.validarMatricula(entradaUsuario)){
           JOptionPane.showMessageDialog(null,"El campo matrícula no es correcto", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
        } else {
            String busqueda = concesionario.buscarVehiculo(entradaUsuario);
            if (busqueda == null){
                JOptionPane.showMessageDialog(null,"No se encuentra el Vehículo", "Error",JOptionPane.ERROR_MESSAGE);
            } else {
                String kms = JOptionPane.showInputDialog(null,"Introduce los Kilómetros"," Modificar Kilómetros", JOptionPane.QUESTION_MESSAGE);
                if (kms.equals("")) {
                    JOptionPane.showMessageDialog(null, "El campo kms está vacío", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
                } else if (!Validar.isMayorQueCero(Integer.valueOf(kms))) {
                    JOptionPane.showMessageDialog(null, "El campo kms debe ser mayor que cero", "Error en la entrada", JOptionPane.ERROR_MESSAGE);
                }else {
                    if (concesionario.actualizarKmsVehiculo(entradaUsuario, Integer.valueOf(kms))){
                        JOptionPane.showMessageDialog(null,"Kilómetros Actualizados", "Actualizando",JOptionPane.INFORMATION_MESSAGE);
                        concesionario.listarVehiculos();
                        
                    }else 
                        JOptionPane.showMessageDialog(null, "No se ha podido realizar la operación", "Error", JOptionPane.ERROR_MESSAGE);
                    
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    
    //mostrar
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //creamos a ventana que conten a tabla
        Mostrar mostrar = new Mostrar(concesionario);
         //a seguinte linea fai que non se cerre a aplicación ó cerrar a ventá de insertar
        mostrar.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        //centramos a ventana
        mostrar.setLocationRelativeTo(null);
        //mostramos a ventana
        mostrar.setVisible(true);

        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
